version: '3'
services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:Phil2:12-1!6@db:5432/llm_evaluation

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local